language: bash
services: docker

env:
  matrix:
    - REPO=apache
    - REPO=base-php
    - REPO=base-python
    - REPO=base-ruby
    - REPO=cachet
    - REPO=drupal-php
    - REPO=drupal6
    - REPO=drupal7
    - REPO=drupal8
    - REPO=httpd
    - REPO=mariadb
    - REPO=matomo
    - REPO=memcached
    - REPO=nginx
    - REPO=node
    - REPO=php
    - REPO=postgres
    - REPO=python
    - REPO=redis
    - REPO=ruby
    - REPO=solr
    - REPO=webgrind
    - REPO=wordpress
    - REPO=wordpress-php

script:
  - set -e
  - |
    docker run -e GITHUB_MACHINE_USER_API_TOKEN -e GITHUB_MACHINE_USER -e GIT_USER_EMAIL --rm -v $PWD:/images \
      wodby/alpine:dev sh -c "cd /images && ./${REPO}.sh"
