language: bash
services: docker

env:
  matrix:
    - REPO=base-php
    - REPO=php

script:
  - set -e
  - |
    docker run -e GITHUB_MACHINE_USER_API_TOKEN -e GITHUB_MACHINE_USER --rm -v $PWD:/images \
      wodby/alpine sh -c "cd /images && ./${REPO}.sh"
