language: bash
services: docker

env:
  matrix:
    - REPO=base-php
    - REPO=base-python
    - REPO=base-ruby
    - REPO=php
    - REPO=python
    - REPO=ruby

script:
  - set -e
  - |
    docker run -e GITHUB_MACHINE_USER_API_TOKEN -e GITHUB_MACHINE_USER -e GIT_USER_EMAIL --rm -v $PWD:/images \
      wodby/alpine:dev sh -c "cd /images && ./${REPO}.sh"
