language: bash
services: docker

env:
  matrix:
    - script=adminer
    - script=adminer-php
    - script=apache
    - script=base-php
    - script=base-python
    - script=base-ruby
    - script=cachet
    - script=cachet-php
    - script=drupal
    - script=drupal-6-php
    - script=drupal-7-php
    - script=drupal-8-php
    - script=drupal-php
    - script=httpd
    - script=mariadb
    - script=matomo
    - script=matomo-php
    - script=memcached
    - script=nginx
    - script=node
    - script=php
    - script=postgres
    - script=python
    - script=redis
    - script=ruby
    - script=solr
    - script=webgrind
    - script=webgrind-php
    - script=wordpress
    - script=wordpress-4-php
    - script=wordpress-php

script:
  - set -e
  - |
      docker run -e GITHUB_MACHINE_USER_API_TOKEN -e GITHUB_MACHINE_USER -e GIT_USER_EMAIL --rm -v $PWD:/images \
            wodby/alpine:dev sh -c "cd /images && ./${script}.sh"

