name: Update

on:
  push:
    branches:
    - master

  schedule:
  - cron: '0 2 * * *'

  pull_request:

jobs:
  repos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        dir: repos
        script: drupal-vanilla
        api_token: ${{ secrets.GIT_GITHUB_MACHINE_USER_API_TOKEN }}
        user: ${{ secrets.GIT_GITHUB_MACHINE_USER }}
        email: ${{ secrets.GIT_USER_EMAIL }}
        name: ${{ secrets.GIT_USER_NAME }}
  forks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        dir: forks
        script: base-solr
        api_token: ${{ secrets.GIT_GITHUB_MACHINE_USER_API_TOKEN }}
        user: ${{ secrets.GIT_GITHUB_MACHINE_USER }}
        email: ${{ secrets.GIT_USER_EMAIL }}
        name: ${{ secrets.GIT_USER_NAME }}
  alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [mariadb,nginx,opensmtpd,varnish]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        dir: alpine
        script: ${{ matrix.script }}
        api_token: ${{ secrets.GIT_GITHUB_MACHINE_USER_API_TOKEN }}
        user: ${{ secrets.GIT_GITHUB_MACHINE_USER }}
        email: ${{ secrets.GIT_USER_EMAIL }}
        name: ${{ secrets.GIT_USER_NAME }}
  images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [alpine,apache,memcached,node,php,postgres,python,redis,ruby,solr]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        dir: images
        script: ${{ matrix.script }}
        api_token: ${{ secrets.GIT_GITHUB_MACHINE_USER_API_TOKEN }}
        user: ${{ secrets.GIT_GITHUB_MACHINE_USER }}
        email: ${{ secrets.GIT_USER_EMAIL }}
        name: ${{ secrets.GIT_USER_NAME }}
  stability-tags:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [drupal-php,wordpress-php,adminer-php,cachet-php,matomo-php,webgrind-php,drupal,wordpress,xhprof]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        dir: stability-tags
        script: ${{ matrix.script }}
        api_token: ${{ secrets.GIT_GITHUB_MACHINE_USER_API_TOKEN }}
        user: ${{ secrets.GIT_GITHUB_MACHINE_USER }}
        email: ${{ secrets.GIT_USER_EMAIL }}
        name: ${{ secrets.GIT_USER_NAME }}
  upstream:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [adminer,cachet,drupal,elasticsearch,kibana,mariadb,matomo,nginx,varnish,webgrind,wordpress,xhprof,]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        dir: upstream
        script: ${{ matrix.script }}
        api_token: ${{ secrets.GIT_GITHUB_MACHINE_USER_API_TOKEN }}
        user: ${{ secrets.GIT_GITHUB_MACHINE_USER }}
        email: ${{ secrets.GIT_USER_EMAIL }}
        name: ${{ secrets.GIT_USER_NAME }}
  docker4x:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [drupal,php,python,ruby,wordpress]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        dir: docker4x
        script: ${{ matrix.script }}
        api_token: ${{ secrets.GIT_GITHUB_MACHINE_USER_API_TOKEN }}
        user: ${{ secrets.GIT_GITHUB_MACHINE_USER }}
        email: ${{ secrets.GIT_USER_EMAIL }}
        name: ${{ secrets.GIT_USER_NAME }}
