name: Update

on:
  push:
    branches:
    - master

  schedule:
  - cron: '0 2 * * *'

  pull_request:
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GITHUB_MACHINE_USER_API_TOKEN: ${{ secrets.GIT_GITHUB_MACHINE_USER_API_TOKEN }}
  GITHUB_MACHINE_USER: ${{ secrets.GIT_GITHUB_MACHINE_USER }}
  GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
  GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}

jobs:
  repos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions
      with:
        dir: repos
        script: [drupal-vanilla,wordpress-vanilla]
  alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [mariadb,nginx,opensmtpd,varnish,squid]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions
      with:
        dir: alpine
        script: ${{ matrix.script }}
  images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [alpine,apache,memcached,node,php,postgres,python,redis,valkey,ruby]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions
      with:
        dir: images
        script: ${{ matrix.script }}
  stability-tags:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [drupal-php,wordpress-php,adminer-php,matomo-php,webgrind-php,laravel-php,drupal,wordpress,xhprof]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions
      with:
        dir: stability-tags
        script: ${{ matrix.script }}
  upstream:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [adminer,cachet,drupal,elasticsearch,kibana,mariadb,matomo,nginx,varnish,webgrind,wordpress,xhprof,]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions
      with:
        dir: upstream
        script: ${{ matrix.script }}
  docker4x:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [drupal,php,python,ruby,wordpress,laravel]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions
      with:
        dir: docker4x
        script: ${{ matrix.script }}
